#encoding: utf8

__author__ = 'Leon'

from panda3d.core import *

MB_MOUSE_DETECT = 1 << 1
MB_TOOL_DETECT = 1 << 2
MB_OBJECT_COLLSITION = 1 << 3
MB_BLOCKED = 1<<4

BIT_MASK_BLOCKED = BitMask32(MB_BLOCKED)
BIT_MASK_MOUSE = BitMask32(MB_MOUSE_DETECT)
BIT_MASK_TOOL = BitMask32(MB_TOOL_DETECT)
BIT_MASK_GROUND = BitMask32(MB_MOUSE_DETECT)
BIT_MASK_OBJECT = BitMask32(MB_TOOL_DETECT | MB_OBJECT_COLLSITION | MB_MOUSE_DETECT)
BIT_MASK_HERO = BitMask32(MB_OBJECT_COLLSITION | MB_MOUSE_DETECT | MB_BLOCKED)

ODE_COMMON = BitMask32(0x00000001)
ODE_CATEGORY_COMMON = BitMask32(0x00000001)

DEBUG = True
SHOW_BOUNDS = False
SHOW_COLLISION_BOX = False
SHOW_COLLISION = False
SHOW_LIGHT_FRUSTUM = False

ENTITY_TYPE_UNKNOWN = 0x0
ENTITY_TYPE_ITEM = 0x1
ENTITY_TYPE_OBJECT = 0x2


