#encoding: utf8

__author__ = 'Leon'

from panda3d.core import *

MB_MOUSE_DETECT = 1 << 1
MB_TOOL_DETECT = 1 << 2
MB_OBJECT_COLLSITION = 1 << 3

BIT_MASK_MOUSE = BitMask32(MB_MOUSE_DETECT)
BIT_MASK_TOOL = BitMask32(MB_TOOL_DETECT)
BIT_MASK_GROUND = BitMask32(MB_MOUSE_DETECT)
BIT_MASK_OBJECT = BitMask32(MB_TOOL_DETECT | MB_OBJECT_COLLSITION | MB_MOUSE_DETECT)
BIT_MASK_HERO = BitMask32(MB_OBJECT_COLLSITION | MB_MOUSE_DETECT)

ODE_COMMON = BitMask32(0x00000001)
ODE_CATEGORY_COMMON = BitMask32(0x00000001)

DEBUG = True
SHOW_BOUNDS = False
SHOW_COLLISION_BOX = False
SHOW_COLLISION = False
SHOW_LIGHT_FRUSTUM = False

